config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'keyOpen' => 'people#openKeyboard'
  get 'keyClose' => 'people#closeKeyboard'

  get '' => 'static_pages#home'
  get 'nav' => 'static_pages#nav'
  get 'people' => 'people#kioskIndex'
  get 'kioskPeople/:id' => 'people#kioskPeople'
  get 'artifacts' => 'static_pages#artifacts'
  get 'artifacts/churchHistory' => 'static_pages#churchHistory'
  get 'artifacts/genocideHistory' => 'static_pages#genocideHistory'
  get 'artifacts/genocideMap' => 'static_pages#genocideMap'
  get 'artifacts/saroyanQuote' => 'static_pages#saroyanQuote'
  get 'artifacts/aroianHistory' => 'static_pages#aroianHistory'
  get 'artifacts/kazarianHistory' => 'static_pages#kazarianHistory'

  get 'admin' => 'people#index'
  get 'admin/newPerson' => 'people#new'
  get 'admin/showPerson/(/:id)' => 'people#show', as: "admin_showPerson"
  get 'admin/editPerson/:id' => 'people#edit', as: "admin_editPerson"
  patch 'admin/showPerson/:id' => 'people#update'
  put 'admin/showPerson/:id' => 'people#update'
  post 'admin/showPerson' => 'people#create';
  delete 'admin/deletePerson/:id' => 'people#destroy', as: "admin_deletePerson"

  get 'admin/background' => 'background_images#index'
  delete 'admin/deleteBackground/:id' => 'background_images#destroy', as: "admin_deleteBackground"
  post 'admin/showBackground' => 'background_images#create';
  get 'admin/newBackground' => 'background_images#new'

end

app/models/person.rb
class Person < ActiveRecord::Base
	has_attached_file :image, styles: {large:"800", medium:"450", small:"300", thumb:"100"},
	:default_url => "missingPerson/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	validates_attachment :image, size: { in:0..800.kilobytes }
	
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    authenticate
    @people = Person.all.reverse_order;
    #@people = Person.order("name ASC").all;
    #@people = Person.where('name LIKE ?', '%melikian%').all
  end

  def authenticate
    authenticate_or_request_with_http_basic('Administration') do |username,password|
      username == 'REDACTED' && password == 'REDACTED'
    end
  end

  def kioskIndex
    system("killall matchbox-keyboard");
    numPerPage = 12
    unless !params[:search].present?
      searchString = params[:search].downcase.strip.gsub(/[^a-z ]/i, '').gsub(' ', '%');
      searchString = '%' + searchString + "%"
      search = Person.where('name LIKE ?', searchString).order("name ASC")
      @totalPages = (search.count.to_f / numPerPage.to_f).ceil
      if !params[:page].present?
        @currentPage = 1
        @people = search.limit(numPerPage)
      else
        @currentPage = params[:page].to_i + 1
        @people = Person.where('name LIKE ?', searchString).order("name ASC").limit(numPerPage).offset(params[:page].to_i*numPerPage);
      end
    else
      search = Person.order("name ASC");
      @totalPages = (search.count / numPerPage).ceil
      if !params[:page].present?
        @currentPage = 1
        @people = search.limit(numPerPage);
      else
        @currentPage = params[:page].to_i + 1
        @people = search.limit(numPerPage).offset((params[:page].to_i)*numPerPage);
      end
    end

  end

  def kioskPeople
    @person = Person.find(params[:id]);
    render layout: false;
  end

  def openKeyboard
    system("sudo -u pi matchbox-keyboard -f arial &");
  end

  def closeKeyboard
    system("killall matchbox-keyboard");
  end

  # GET /people/1
  # GET /people/1.json
  def show
    authenticate
  end

  # GET /people/new
  def new
    authenticate
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
    authenticate
  end

  def updateBackup
    system("REDACTED");
    system("REDACTED");
  end

  # POST /people
  # POST /people.json
  def create
    authenticate
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to admin_showPerson_url(@person), notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
    updateBackup
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    authenticate
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to admin_showPerson_url(@person), notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
    updateBackup
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    authenticate
    @person.destroy
    respond_to do |format|
      format.html { redirect_to admin_path, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
    updateBackup
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :birthdate, :birthplace, :deathdate, :deathplace, :story, :image)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for @person, url: admin_showPerson_path(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Date of Birth" %><br>
    <%= f.text_field :birthdate %>
  </div>
  <div class="field">
    <%= f.label "From" %><br>
    <%= f.text_field :birthplace %>
  </div>
  <div class="field">
    <%= f.label "Date of Death" %><br>
    <%= f.text_field :deathdate %>
  </div>
  <div class="field">
    <%= f.label "Place of Death" %><br>
    <%= f.text_field :deathplace %>
  </div>
  <div class="field">
    <%= f.label "Description" %><br>
    <%= f.text_area :story %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/closeKeyboard.html.erb
<h1>People#closeKeyboard</h1>
<p>Find me in app/views/people/closeKeyboard.html.erb</p>

app/views/people/edit.html.erb
<div class="navbar" id="adminpage">
<%= link_to 'Back', admin_path, class: "searchButton", style:"padding-left:50px;padding-top:25px"%>
</div>

<div class="content" id="formpage">
<h1>Editing Person</h1>

<%= render 'form' %>

</div>

app/views/people/index.html.erb
<div class="navbar" id="adminpage">
  <%= link_to '+ New Person', admin_newPerson_path, class: "searchButton" %>
  <%= link_to 'Backgrounds', admin_background_path, class: "searchButton", style: "margin-left: 150px;padding-left:10px;width:125px;padding-top:20px;height:40px" %>
  <h1>Total People: <%= @people.count %></h1>
</div>

<div class="content">
  <p id="notice"><%= notice %></p>

  <br/>
  <br>

  <table>
    <thead>
      <tr>
        <th>Image</th>
        <th>Name</th>
        <th>Birthdate</th>
        <th>From</th>
        <th>Deathdate</th>
        <th>Deathplace</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @people.each do |person| %>
        <tr>
          <td><%= image_tag(person.image.url(:thumb)) %></td>
          <td><%= person.name %></td>
          <td><%= person.birthdate %></td>
          <td><%= person.birthplace %></td>
          <td><%= person.deathdate %></td>
          <td><%= person.deathplace %></td>
          <td><%= link_to 'Show', admin_showPerson_path(person) %></td>
          <td><%= link_to 'Edit', admin_editPerson_path(person) %></td>
          <td><%= link_to 'Delete', admin_deletePerson_path(person), data: { confirm: 'Are you sure?' }, method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
</div>

app/views/people/kioskIndex.html.erb
<%= render :partial => "shared/redirectsHome" %>

<script type="text/javascript">
showPerson=function(id){
  var request = new XMLHttpRequest();
  request.open('get', "/kioskPeople/" + id, false);
  request.send(null);
  var $overlayDiv = $("<div class='overlayDiv'></div>");
  $("body").append($overlayDiv);
  $overlayDiv.append(request.response);
}
$(document).ready(function(){
  $(".peoplepage").on("click touchend",function(){
    if($('.overlayDiv').length){
      $('.overlayDiv').remove();
    }
    else if ($(event.target).is("#textBox")){
        var request = new XMLHttpRequest();
        request.open('get', '/keyOpen', false);
        request.send(null);
    }
    else if ($(event.target).is(".personbox")){
      var request = new XMLHttpRequest();
      request.open('get', '/keyClose', false);
      request.send(null);
      showPerson($(event.target).attr("id"));
    }
    else if ($(event.target).parent().is(".personbox")){
      var request = new XMLHttpRequest();
      request.open('get', '/keyClose', false);
      request.send(null);
      showPerson($(event.target).parent().attr("id"));
    }
    else if(!$(event.target).is("input")){
      var request = new XMLHttpRequest();
      request.open('get', '/keyClose', false);
      request.send(null);
    }
  });
});
</script>

<div class='peoplepage'>
  <div class="navbar">
  <%= button_to "Back", {controller: :static_pages, action: :nav}, {id: "backButton", class: "searchButton", method: :get}%>
  <% if !(params[:search].nil?) && !(params[:search].empty?) %>
    <%= button_to "Clear", {controller: :people, action: :kioskIndex}, {id: "clearButton", class: "searchButton", method: :get}%>
  <% end %>
  <%= form_tag({controller: :people, action: :kioskIndex, page: 1}, id: "searchForm" ,method: "get") do %>
  <input type="text" name="search" id="textBox" value=<%= params[:search] %>>
  <input type="submit" class="searchButton" id="searchButton" value="Search">
  <% end %>
  </div>

  <div class="peoplebox">

    <ul>
      <% @people.each do |person| %>
          <div class="personbox" id=<%= person.id %>>
            <%= image_tag(person.image.url(:thumb)) %>
            <h2><%= person.name %></h2>

            <% if !person.birthdate.blank? && person.deathdate.blank? %>
              <p>Born: <%= person.birthdate %></p>
            <% elsif person.birthdate.blank? && !person.deathdate.blank? %>
              <p>Died: <%= person.deathdate %></p>
            <% elsif !person.birthdate.blank? && !person.deathdate.blank? %>
              <p><%= person.birthdate %> - <%= person.deathdate %></p>
            <% end %>

            <% if !person.birthplace.blank? && person.deathplace.blank? %>
              <p><%= person.birthplace %></p>
            <% elsif person.birthplace.blank? && !person.deathplace.blank? %>
              <p><%= person.deathplace %></p>
            <% elsif !person.birthplace.blank? && !person.deathplace.blank? %>
              <p><%= person.birthplace %> - <%= person.deathplace %></p>
            <% end %>
          </div>
      <% end %>
    </ul>

    <br>
  </div>

  <div class="pagebar">
    <hr>
      <center>
	<% unless @totalPages == 0 %>
          <% unless @currentPage == 1 %>
            <%= button_to "Previous",{controller: :people, action: :kioskIndex}, {id: "prevButton", class: "searchButton", method: :get, params: {page: @currentPage-2, search: params[:search]}, style: "display:inline;"}%>
          <% else %>
            <p id="leftButton">Previous</p>
          <% end %>
          <h1 style="display:inline;">Page <%= @currentPage %> of <%= @totalPages %></h1>
          <% unless @currentPage == @totalPages %>        
            <%= button_to "Next",{controller: :people, action: :kioskIndex}, {id: "nextButton", class: "searchButton", method: :get, params: {page: @currentPage, search: params[:search]}} %>
          <% else %>
            <p id="rightButton">Next</p>
          <% end %>
	<% else %>
	  <p id="leftButton">Previous</p>
	  <h1 style="display:inline;">No results</h1>
	  <p id="rightButton">Next</p>
	<% end %>
      </center>
  </div>

</div>

app/views/people/kioskPeople.html.erb
<%= image_tag(@person.image.url(:medium)) %>
<div class="textArea">
  <span id="name"><%= @person.name %></h1></span>
  <span id="datestring">
    <% if !@person.birthdate.blank? && @person.deathdate.blank? %>
      <p>Born: <%= @person.birthdate %></p>
    <% elsif @person.birthdate.blank? && !@person.deathdate.blank? %>
      <p>Died: <%= @person.deathdate %></p>
    <% elsif !@person.birthdate.blank? && !@person.deathdate.blank? %>
      <p><%= @person.birthdate %> - <%= @person.deathdate %></p>
    <% end %>
  </span>
  <span id="placestring">
    <% if !@person.birthplace.blank? && @person.deathplace.blank? %>
      <p><%= @person.birthplace %></p>
    <% elsif @person.birthplace.blank? && !@person.deathplace.blank? %>
      <p><%= @person.deathplace %></p>
    <% elsif !@person.birthplace.blank? && !@person.deathplace.blank? %>
      <p><%= @person.birthplace %> - <%= @person.deathplace %></p>
    <% end %>
  </span>
  <span id="story"><%= @person.story %></span>
</div>

app/views/people/new.html.erb
<div class="navbar" id="adminpage">
<%= link_to 'Back', admin_path, class: "searchButton", style:"padding-left:50px;padding-top:25px"%>
</div>

<div class="content" id="formpage">
<h1>New Person</h1>

<%= render 'form' %>
</div>

app/views/people/openKeyboard.html.erb
<h1>People#openKeyboard</h1>
<p>Find me in app/views/people/openKeyboard.html.erb</p>

app/views/people/show.html.erb
<div class="navbar" id="adminpage">
<%= link_to 'Back', admin_path, class: "searchButton", style:"padding-left:50px;padding-top:25px"%>
</div>


<div class="content" id="formpage">
<br><br>
<%= image_tag(@person.image.url(:small)) %>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Date of Birth:</strong>
  <%= @person.birthdate %>
</p>

<p>
  <strong>From:</strong>
  <%= @person.birthplace %>
</p>

<p>
  <strong>Date of Death:</strong>
  <%= @person.deathdate %>
</p>

<p>
  <strong>Place of Death:</strong>
  <%= @person.deathplace %>
</p>

<p>
  <strong>Description:</strong>
  <%= @person.story %>
</p>

<%= link_to 'Edit', admin_editPerson_path(@person) %> |
</div>