config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'keyOpen' => 'people#openKeyboard'
  get 'keyClose' => 'people#closeKeyboard'

  get '' => 'static_pages#home'
  get 'nav' => 'static_pages#nav'
  get 'people' => 'people#kioskIndex'
  get 'kioskPeople/:id' => 'people#kioskPeople'
  get 'artifacts' => 'static_pages#artifacts'
  get 'artifacts/churchHistory' => 'static_pages#churchHistory'
  get 'artifacts/genocideHistory' => 'static_pages#genocideHistory'
  get 'artifacts/genocideMap' => 'static_pages#genocideMap'
  get 'artifacts/saroyanQuote' => 'static_pages#saroyanQuote'
  get 'artifacts/aroianHistory' => 'static_pages#aroianHistory'
  get 'artifacts/kazarianHistory' => 'static_pages#kazarianHistory'

  get 'admin' => 'people#index'
  get 'admin/newPerson' => 'people#new'
  get 'admin/showPerson/(/:id)' => 'people#show', as: "admin_showPerson"
  get 'admin/editPerson/:id' => 'people#edit', as: "admin_editPerson"
  patch 'admin/showPerson/:id' => 'people#update'
  put 'admin/showPerson/:id' => 'people#update'
  post 'admin/showPerson' => 'people#create';
  delete 'admin/deletePerson/:id' => 'people#destroy', as: "admin_deletePerson"

  get 'admin/background' => 'background_images#index'
  delete 'admin/deleteBackground/:id' => 'background_images#destroy', as: "admin_deleteBackground"
  post 'admin/showBackground' => 'background_images#create';
  get 'admin/newBackground' => 'background_images#new'

end

app/models/background_image.rb
class BackgroundImage < ActiveRecord::Base
	has_attached_file :image, styles: { small: "500",large: "1280x1024" }
validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
validates_attachment :image, size: { in:0..10000.kilobytes }
validate :image_dimensions

  private

  def image_dimensions
    required_width  = 1280
    required_height = 1024
    dimensions = Paperclip::Geometry.from_file(image.queued_for_write[:original].path)

    errors.add(:image, "Width must be #{required_width}px") unless dimensions.width == required_width
    errors.add(:image, "Height must be #{required_height}px") unless dimensions.height == required_height
  end

end

app/controllers/background_images_controller.rb
class BackgroundImagesController < ApplicationController
  before_action :set_background_image, only: [:show, :edit, :update, :destroy]


  def authenticate
    authenticate_or_request_with_http_basic('Administration') do |username,password|
      username == 'REDACTED' && password == 'REDACTED'
    end
  end

  # GET /background_images
  # GET /background_images.json
  def index
    authenticate
    @background_images = BackgroundImage.all
  end

  # GET /background_images/1
  # GET /background_images/1.json
  def show
    authenticate
  end

  # GET /background_images/new
  def new
    authenticate
    @background_image = BackgroundImage.new
  end

  # GET /background_images/1/edit
  def edit
    authenticate
  end

  # POST /background_images
  # POST /background_images.json
  def create
    authenticate
    @background_image = BackgroundImage.new(background_image_params)

    respond_to do |format|
      if @background_image.save
        format.html { redirect_to admin_background_path , notice: 'Background image was successfully created.' }
        format.json { render :show, status: :created, location: @background_image }
      else
        format.html { render :new }
        format.json { render json: @background_image.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /background_images/1
  # PATCH/PUT /background_images/1.json
  #def update
   # authenticate
   # respond_to do |format|
  #    if @background_image.update(background_image_params)
  #      format.html { redirect_to @background_image, notice: 'Background image was successfully updated.' }
  #      format.json { render :show, status: :ok, location: @background_image }
  #    else
  #      format.html { render :edit }
  #      format.json { render json: @background_image.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end


  # DELETE /background_images/1
  # DELETE /background_images/1.json
  def destroy
    authenticate
    @background_image.destroy
    respond_to do |format|
      format.html { redirect_to admin_background_url, notice: 'Background image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_background_image
      @background_image = BackgroundImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def background_image_params
      params.require(:background_image).permit(:image)
    end
end

app/helpers/background_images_helper.rb
module BackgroundImagesHelper
end

app/views/background_images/_form.html.erb
<%= form_for @background_image, url: admin_showBackground_path(@background_image) do |f| %>
  <% if @background_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@background_image.errors.count, "error") %> prohibited this background_image from being saved:</h2>

      <ul>
      <% @background_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Background Image:" %><br><br>
    <%= f.file_field :image %>
  </div>
  <br><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/background_images/edit.html.erb
<h1>Editing Background Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @background_image %> |
<%= link_to 'Back', background_images_path %>

app/views/background_images/index.html.erb
<div class="navbar" id="adminpage">
  <%= link_to '+ New Background', admin_newBackground_path, class: "searchButton", style: "padding-left:25px;width:125px" %>
  <%= link_to 'People', admin_path, class: "searchButton", style: "margin-left: 160px;padding-left:42px;width:108px;padding-top:20px;height:40px" %>
</div>

<div class="backGroundcontent" style="padding-top:20px">
  <table>
    <tbody>
      <% @background_images.each do |background_image| %>
        <tr>
          <td><%= image_tag(background_image.image(:small)) %></td> 
          <td><%= link_to 'Delete', admin_deleteBackground_path(background_image), data: { confirm: 'Are you sure?' }, method: :delete %></td>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br />
  <br />
</div>

app/views/background_images/new.html.erb
<div class="navbar" id="adminpage">
<%= link_to 'Back', admin_background_path, class: "searchButton", style:"padding-left:50px;width:100px;padding-top:20px;height:40px;"%>
</div>

<div class="content" id="formpage" style="width:50%">
<h1>New Background</h1>

<%= render 'form' %>
</div>

app/views/background_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@background_image.image(:small)) %>
</p>

<%= link_to 'Edit', edit_background_image_path(@background_image) %> |
<%= link_to 'Back', background_images_path %>